name: 'Checkout'

on: workflow_dispatch

jobs:
  builds-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: hello
        run: echo "hello world0"
